### ISSUE TITLE
Sidebar is not displaying after after user logged into the portal

### ISSUE THREAD

**Issue by ChrisDinhNZ** [ChrisDinhNZ/MultilinksPortal#43]
After the user have been authenticated the portal will try to create a websocket connection (for real-time communication) with Multilinks Core.

The shared-header component contains a sidebar which is displayed only if both, user is logged in and websocket connection is active. Currently the sidebar is not being displayed so both of these conditions are not met.

**Comment by ChrisDinhNZ** [comment]
This is actually quite an easy one. There is a typo (case-sensitive) in `shared-header.component.ts`.

**Comment by iamhabee** [comment]
hi @ChrisDinhNZ please can i fix this

**Comment by ChrisDinhNZ** [comment]
@iamhabee, yes please.

**Comment by iamhabee** [comment]
alright tnx

**Comment by iamhabee** [comment]
am sorry for disturbing but i av been checking the shared-header.component file and i couldnt find any typo error and yet it doesnt appear to av a bug, please any hint will be appreciated

**Comment by ChrisDinhNZ** [comment]
@iamhabee I think the problem is `this.coreService.connectionActive$.subscribe((connectionActive)` doesn't get executed at run-time. If we were to declare `SharedHeaderComponent implements OnInit` I think the typescript compiler would have warned us about it.

**Comment by ChrisDinhNZ** [comment]
@iamhabee did you have any more luck with this?

**Comment by iamhabee** [comment]
Am sorry for my late reply, am out of data but I will complete it today and make a PR tomorrow

**Comment by ChrisDinhNZ** [comment]
Need to resolve this as it is blocking other issues

**Comment by iamhabee** [comment]
Am sorry for any inconviniency I might caused. I try so much to make it up early but it seem my challenges won't allow me.
Am greatful for giving me d chance to try out.
Thanks

**Comment by ChrisDinhNZ** [comment]
@iamhabee  Don't be sorry, thanks for giving it a go. Unfortunately only when I started looking at other issues that I realised it would make more sense to resolve this one first.
