### ISSUE TITLE
Add placeholder "About" item to top nav-bar

### ISSUE THREAD

**Issue by ChrisDinhNZ** [ChrisDinhNZ/MultilinksPortal#46]
After the user logged into the portal, the nav-bar at the top will change to reflect the actions available to a logged in user. Currently there is only 1 item i.e. **Sign Out** button.

We want to add another button **About** which will expand to show the details about the current portal (however for this task we just want to add the button, clicking on it will do nothing).

Code-wise we want to update `user-navbar-top.component.html` by adding `About` before the `Sign Out` button.

**Comment by kidkrub** [comment]
Can I try to tackle this?

**Comment by Thuvan96** [comment]
Can i work on this ?

**Comment by ChrisDinhNZ** [comment]
Yes that would be great. But I think I messed up the description. The html markup will be pretty the same as the `Sign Out` button.
Except the css class will be `class="fa fa-info-circle"`.
`(click)="signout()"` can be deleted because we don't need the button to do anything at the moment.

**Comment by ChrisDinhNZ** [comment]
Sorry @Thuvan96, @kidkrub was first in line.

**Comment by ChrisDinhNZ** [comment]
Sorry @kidkrub, @Thuvan96 was first in line

**Comment by ChrisDinhNZ** [comment]
I do apologize. My first time participating in Hacktoberfest. Must be a process to assign who works on it.

**Comment by ChrisDinhNZ** [comment]
All fun and games 😀
