### ISSUE TITLE
Need some spacing between Confirm and Deny button for links pending confirmation

### ISSUE THREAD

**Issue by ChrisDinhNZ** [ChrisDinhNZ/MultilinksPortal#73]
We want to add 5px horizontal margin between these buttons.

1. Open styles.css
2. Under the `.chat li .chat-body p` class, add the following:

> .chat li .chat-body button {
>    margin: 0 5px;
> }
>

**Comment by jazzninja** [comment]
Go it. Will submit a pull request shortly.

**Comment by jazzninja** [comment]
PR request submitted
